pipeline:
  name: sdsd
  identifier: sdsd
  projectIdentifier: ankittest
  orgIdentifier: Ankit_test
  tags: {}
  stages:
    - stage:
        name: asdad
        identifier: asdad
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "dsf"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
